default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: dss851566
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: testapp3

production:
  <<: *default
  database: testapp3
